<?php

/**
 * @file
 * Module hooks for the Islandora REST API Auth module.
 */

/**
 * Implements hook_init().
 */
function islandora_rest_api_auth_init() {
  islandora_rest_api_auth_authenticate();
}

/**
 * Implements hook_form__FORMID_alter().
 */
function islandora_rest_api_auth_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  if ($form_state['user']->uid == $user->uid) {
    module_load_include('inc', 'islandora_rest', 'includes/utilities');
    $access = FALSE;
    foreach (user_role_permissions($user->roles) as $perms) {
      if (array_intersect_key(islandora_rest_permission(), $perms)) {
        $access = TRUE;
        break;
      }
    }
    if ($access) {
      $form['islandora_rest_api_auth_token'] = array(
        '#type' => 'password',
        '#title' => t('Islandora REST API Authentication Token'),
        '#description' => t('NOTE: The stored version is salted. Once a token has been stored and salted it is no longer able to be retrieved.'),
      );
      $form['#submit'][] = 'islandora_rest_api_auth_token_submit';
    }
  }
}

/**
 * Authenticates the REST user.
 */
function islandora_rest_api_auth_authenticate() {
  if (strpos(current_path(), 'islandora/rest/') === 0) {
    if (isset($_SERVER['HTTP_AUTHORIZATION'])) {
      $authheader = $_SERVER['HTTP_AUTHORIZATION'];
    }
    if (isset($authheader) && !empty($authheader)) {
      module_load_include('inc', 'islandora_rest_api_auth', 'includes/utilities');
      list($username, $token) = explode(':', base64_decode(substr($authheader, 6)));
      if (islandora_rest_api_auth_authenticate_token($username, $token)) {
        islandora_rest_api_auth_login($username);
      }
      else {
        header('HTTP/1.0 401 Unauthorized', TRUE);
        exit;
      }
    }
  }
}

/**
 * Logs in the REST user.
 *
 * @param string $username
 *   The name of the user trying to login.
 *
 * @see https://www.drupal.org/node/218104
 */
function islandora_rest_api_auth_login($username) {
  global $user;
  drupal_save_session(FALSE);
  $user = user_load_by_name($username);
}

/**
 * Submit handler for generating and storing a token.
 */
function islandora_rest_api_auth_token_submit($form, $form_state) {
  $raw_token = $form_state['values']['islandora_rest_api_auth_token'];
  // Don't override with an empty token.
  if (!empty($raw_token)) {
    global $user;
    module_load_include('inc', 'islandora_rest_api_auth', 'includes/db');
    islandora_rest_api_auth_upsert_token($user->uid, $raw_token);
  }
}

/**
 * Implements hook_user_delete().
 */
function islandora_rest_api_auth_user_delete($account) {
  module_load_include('inc', 'islandora_rest_api_auth', 'includes/db');
  islandora_rest_api_auth_delete_token($account->uid);
}
